#!/bin/bash

# Agent Context Protocol (ACP) Update Script
# This script updates AGENT.md, template files, and utility scripts from the repository

# Self-relocation guard: this script overwrites itself during the update
# (it copies the latest version from the repo to agent/scripts/). Bash reads
# files lazily by byte offset, so the overwrite garbles execution. Fix: re-exec
# from a temp copy so the file on disk can safely change.
if [ -z "$_ACP_UPDATE_RELOCATED" ]; then
    _tmp_copy=$(mktemp)
    cp "$0" "$_tmp_copy"
    export _ACP_UPDATE_RELOCATED=1
    bash "$_tmp_copy" "$@"
    _rc=$?
    rm -f "$_tmp_copy"
    exit $_rc
fi

set -e
trap 'echo "ERROR: $(basename "$0") failed at line $LINENO -- check output above for details." >&2; exit 1' ERR

# Colors for output using tput (more reliable than ANSI codes)
if command -v tput >/dev/null 2>&1 && [ -t 1 ]; then
    RED=$(tput setaf 1)
    GREEN=$(tput setaf 2)
    YELLOW=$(tput setaf 3)
    BLUE=$(tput setaf 4)
    BOLD=$(tput bold)
    NC=$(tput sgr0)
else
    RED=''
    GREEN=''
    YELLOW=''
    BLUE=''
    BOLD=''
    NC=''
fi

# Repository details
REPO_URL="https://github.com/ssucipto/acp-enhanced.git"
BRANCH="mainline"

echo "${BLUE}Agent Context Protocol (ACP) Updater${NC}"
echo "======================================"
echo ""

# Check if AGENT.md exists
if [ ! -f "AGENT.md" ]; then
    echo "${RED}Error: AGENT.md not found in current directory${NC}"
    echo "This script should be run from your project root where AGENT.md is located."
    exit 1
fi

# Create temporary directory
TEMP_DIR=$(mktemp -d)
trap "rm -rf $TEMP_DIR" EXIT

echo "Fetching latest ACP files..."
if ! git clone --depth 1 --branch "$BRANCH" "$REPO_URL" "$TEMP_DIR" &>/dev/null; then
    echo "${RED}Error: Failed to fetch repository${NC}"
    echo "Please check your internet connection and try again."
    exit 1
fi

echo "${GREEN}✓${NC} Latest files fetched"
echo ""

# ── Legacy .agent/ migration ──────────────────────────────────────────────────
# Detect ACP < 6.x layout and auto-merge user-state files into agent/ before
# the update proceeds. Static files (.agent/core, skills, wiki) are dropped —
# they will be refreshed by the update anyway.
if [ -d ".agent" ]; then
    echo "${YELLOW}Found legacy .agent/ directory — auto-migrating to agent/ layout...${NC}"

    # User-state memory files (create-if-absent: never overwrite)
    if [ -d ".agent/memory" ]; then
        mkdir -p agent/memory
        for _f in sessions.md lessons.md decisions.md patterns.md; do
            if [ -f ".agent/memory/$_f" ] && [ ! -f "agent/memory/$_f" ]; then
                mv ".agent/memory/$_f" "agent/memory/$_f"
                echo "  ✓ Migrated memory/$_f"
            fi
        done
    fi

    # Routing task files (route-NNN.md — user-created, never overwrite)
    if [ -d ".agent/tasks" ]; then
        mkdir -p agent/routing/tasks
        for _f in ".agent/tasks/task-"*.md; do
            [ -f "$_f" ] || continue
            _dest="agent/routing/tasks/$(basename "$_f")"
            if [ ! -f "$_dest" ]; then
                mv "$_f" "$_dest"
                echo "  ✓ Migrated routing/tasks/$(basename "$_f")"
            fi
        done
    fi

    # Routing ledger (user-state — never overwrite)
    if [ -f ".agent/routing/ledger.md" ] && [ ! -f "agent/routing/ledger.md" ]; then
        mkdir -p agent/routing
        mv ".agent/routing/ledger.md" "agent/routing/ledger.md"
        echo "  ✓ Migrated routing/ledger.md"
    fi

    rm -rf ".agent"
    echo "${GREEN}✓${NC} Legacy .agent/ merged and removed"
    echo ""
fi

# Ensure reports directory exists and is ignored
mkdir -p "agent/reports"
if [ ! -f "agent/.gitignore" ]; then
    echo "Creating agent/.gitignore..."
    cat > "agent/.gitignore" << 'EOF'
# Agent Context Protocol - Local Files
# These files are generated locally and should not be committed

# Reports directory - generated by /acp-report command
reports/
clarifications/
feedback/
drafts/
preferences/
EOF
    echo "${GREEN}✓${NC} Created agent/.gitignore"
fi

echo "Updating ACP files..."

# Update template files (only .template.md files from these directories)
find "$TEMP_DIR/agent/design" -maxdepth 1 -name "*.template.md" -exec cp {} "agent/design/" \;
find "$TEMP_DIR/agent/milestones" -maxdepth 1 -name "*.template.md" -exec cp {} "agent/milestones/" \;
find "$TEMP_DIR/agent/patterns" -maxdepth 1 -name "*.template.md" -exec cp {} "agent/patterns/" \;
find "$TEMP_DIR/agent/tasks" -maxdepth 1 -name "*.template.md" -exec cp {} "agent/tasks/" \;

# Update command template
mkdir -p "agent/commands"
cp "$TEMP_DIR/agent/commands/command.template.md" "agent/commands/"

# Update all command files (flat structure with dot notation)
# Copies files like acp.init.md, acp.status.md, deploy.production.md, etc.
if [ -d "$TEMP_DIR/agent/commands" ]; then
    find "$TEMP_DIR/agent/commands" -maxdepth 1 -name "*.*.md" -exec cp {} "agent/commands/" \;
fi

# Update progress template
cp "$TEMP_DIR/agent/progress.template.yaml" "agent/"

# Update manifest template
if [ -f "$TEMP_DIR/agent/manifest.template.yaml" ]; then
    cp "$TEMP_DIR/agent/manifest.template.yaml" "agent/"
fi

# Update package template
if [ -f "$TEMP_DIR/agent/package.template.yaml" ]; then
    cp "$TEMP_DIR/agent/package.template.yaml" "agent/"
fi

# Update AGENT.md
cp "$TEMP_DIR/AGENT.md" "."

# Update all scripts (*.sh files)
# This ensures all current and future scripts are copied
if [ -d "$TEMP_DIR/agent/scripts" ]; then
    find "$TEMP_DIR/agent/scripts" -maxdepth 1 -name "*.sh" -exec cp {} "agent/scripts/" \;
    chmod +x agent/scripts/*.sh
fi

# Clean up deprecated scripts (from versions < 2.0.0)
. "agent/scripts/acp.common.sh"
init_colors
cleanup_deprecated_scripts

echo "${GREEN}✓${NC} All files updated"
echo ""

# ACP Enhanced — update static context files (preserve user-state files)
echo "Updating ACP Enhanced context layer..."
mkdir -p agent/core agent/memory agent/routing/tasks agent/skills agent/wiki

# Overwrite static files (no user state in these)
[ -d "$TEMP_DIR/agent/core" ]   && cp "$TEMP_DIR/agent/core/"*.yml   agent/core/   2>/dev/null || true
[ -d "$TEMP_DIR/agent/skills" ] && cp "$TEMP_DIR/agent/skills/"*.md  agent/skills/ 2>/dev/null || true
if [ -d "$TEMP_DIR/agent/wiki" ]; then
    cp "$TEMP_DIR/agent/wiki/"*.yml agent/wiki/ 2>/dev/null || true
    cp "$TEMP_DIR/agent/wiki/"*.md  agent/wiki/ 2>/dev/null || true
fi
if [ -d "$TEMP_DIR/agent/routing" ]; then
    cp "$TEMP_DIR/agent/routing/taxonomy.yml" agent/routing/ 2>/dev/null || true
    cp "$TEMP_DIR/agent/routing/rules.md"     agent/routing/ 2>/dev/null || true
    cp "$TEMP_DIR/agent/routing/config.yml"   agent/routing/ 2>/dev/null || true
    # route-template only — never overwrite user routing task files
    cp "$TEMP_DIR/agent/routing/tasks/route-template.md" \
       agent/routing/tasks/ 2>/dev/null || true
fi

# Preserve user-state files — create only if somehow missing
[ -f "agent/memory/sessions.md"  ] || echo "# Session Memory"    > agent/memory/sessions.md
[ -f "agent/memory/lessons.md"   ] || echo "# Lessons Log"       > agent/memory/lessons.md
[ -f "agent/memory/decisions.md" ] || echo "# ADR Log"           > agent/memory/decisions.md
[ -f "agent/memory/patterns.md"  ] || echo "# Reusable Patterns" > agent/memory/patterns.md
[ -f "agent/routing/ledger.md"   ] || echo "# Routing Ledger"    > agent/routing/ledger.md

# Update opencode slash commands (static generated artifact — always overwrite)
if [ -d "$TEMP_DIR/.opencode/commands" ]; then
    mkdir -p .opencode/commands
    cp "$TEMP_DIR/.opencode/commands/"*.md .opencode/commands/ 2>/dev/null || true
fi

echo "${GREEN}✓${NC} ACP Enhanced context layer updated"
echo ""

# Update acp-core version in manifest if it exists
if [ -f "agent/manifest.yaml" ]; then
    echo "Updating manifest..."
    
    # Get new ACP version
    NEW_VERSION=$(grep "^\*\*Version\*\*:" "AGENT.md" | sed 's/.*: //' | head -1)
    UPDATE_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    
    # Update acp-core version and timestamps
    _sed_i "/^  acp-core:/,/^  [a-z]/ {
        s/package_version: .*/package_version: ${NEW_VERSION}/
        s/updated_at: .*/updated_at: ${UPDATE_DATE}/
    }" agent/manifest.yaml

    # Update manifest timestamp
    _sed_i "s/^last_updated: .*/last_updated: ${UPDATE_DATE}/" agent/manifest.yaml
    
    echo "${GREEN}✓${NC} Updated acp-core to v${NEW_VERSION} in manifest.yaml"
    echo ""
fi

echo "${GREEN}Update complete!${NC}"
echo ""
echo "${BLUE}What was updated:${NC}"
echo "  ✓ AGENT.md (methodology documentation)"
echo "  ✓ Template files (design, milestone, task, pattern)"
echo "  ✓ Command files (all ACP commands)"
echo "  ✓ Utility scripts (update, check-for-updates, version, etc.)"
echo "  ✓ ACP Enhanced context layer (agent/core/, agent/skills/, agent/wiki/, agent/routing/)"
echo "  ✓ opencode slash commands (.opencode/commands/)"
echo ""
echo "${BLUE}Next steps:${NC}"
echo "1. Review changes: git diff"
echo "2. See what changed: git status"
echo "3. Revert if needed: git checkout <file>"
echo ""
echo "For detailed changelog:"
echo "  https://github.com/ssucipto/acp-enhanced/blob/mainline/CHANGELOG.md"
echo ""
display_available_commands
echo ""
echo "${BLUE}For AI agents:${NC}"
echo "Type '${GREEN}/acp-init${NC}' to reload context with updated files."
echo ""
